# Using dart-define or dart-define-from-file is not required.
# You can use any other method to provide these values i.e config file, .env file or just hard code them.
run:
	@# Check example.env to see how .env file should look like.
	flutter run --dart-define-from-file=./.env
