arb-dir: lib/src/l10n/translations
template-arb-file: app_en.arb
output-dir: lib/src/l10n/generated
output-localization-file: app_localizations.dart
nullable-getter: true
untranslated-messages-file: build/untranslated_messages.json
output-class: ReclaimAppLocalizations
use-named-parameters: true
