name: reclaim_inapp_sdk
description: Pre-built widgets library to export user's data with provable authenticity using HTTPS & Reclaim Protocol Zero-knowledge proof technology
version: 0.12.0
homepage: https://reclaimprotocol.org
repository: https://github.com/reclaimprotocol/reclaim-inapp-sdk.git

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  flutter_inappwebview: 6.1.5
  flutter_inappwebview_android: 1.1.3
  flutter_inappwebview_ios: 1.1.2
  flutter_inappwebview_platform_interface: 1.3.0+1
  fluttertoast: ^8.0.0
  uuid: ^4.4.0
  native_dio_adapter: ^1.3.0
  device_info_plus: ^11.2.0
  dio: ^5.0.0
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
  path_provider: ^2.0.0
  crypto: ^3.0.0
  flutter_svg: ^2.0.0
  logging: ^1.2.0
  intl: ^0.20.1
  yaml: ^3.0.0
  package_info_plus: ^8.0.2
  dio_smart_retry: ^7.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.4.1
  clock: ^1.1.1
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  permission_handler: ^12.0.0+1
  pool: ^1.0.0
  meta: ^1.0.0
  pointycastle: ^4.0.0
  measure_performance: ^1.2.0
  equatable: ^2.0.7
  xxh3: ^1.2.0
  async: ^2.12.0
  synchronized: ^3.3.1
  http: ^1.3.0
  path: ^1.9.1
  cupertino_http: ^2.1.1
  cronet_http: ^1.3.3
  simple_shimmer: ^0.1.0+1
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  mesh: ^0.5.0
  retry: ^3.1.2
  convert: ^3.1.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/animated_icons/
    - assets/icons/
    - assets/icons/claim_creation/
    - pubspec.yaml
