name: reclaim_inapp_flutter_sdk
description: Reclaim Protocol's InApp Flutter SDK for ZK proof generations for requests with an in-app experience of web verification
version: 0.8.3
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  reclaim_inapp_sdk:
    path: internal/sdk
  reclaim_gnark_zkoperator:
    path: internal/zkoperator
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
