name: reclaim_inapp_flutter_sdk
description: Reclaim Protocol's InApp Flutter SDK for ZK proof generations for requests with an in-app experience of web verification
version: 0.10.13
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  reclaim_inapp_sdk:
    git:
      url: https://github.com/reclaimprotocol/reclaim-inapp-flutter-sdk.git
      ref: 0.10.13
      path: internal/sdk
  reclaim_gnark_zkoperator:
    git:
      url: https://github.com/reclaimprotocol/reclaim-inapp-flutter-sdk.git
      ref: 0.10.13
      path: internal/zkoperator
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
