import 'package:json_annotation/json_annotation.dart';

import '../../webview_utils.dart';
import '../generated/app_localizations.dart';

part 'remote_l10n.g.dart';

// translations getters generated by flutter aren't generated for this file.
// we need to add those manually
@JsonSerializable()
class RemoteLocalizations extends ReclaimAppLocalizations {
  RemoteLocalizations({
    required this.locale,
    required this.helloWorld,
    required this.allow,
    required this.almostThereJustFinalizingTheDetails,
    required this.anUnknownProblemOccurred,
    required this.areYouSureYouSeeAllTheDataThatNeedsVerification,
    required this.byContinuingYouAgreeToThese,
    required this.contactApplicationSupportForMoreInformation,
    required this.copiedToYourClipboard,
    required this.copySessionId,
    required this.createAndVerifyDataInSeconds,
    required this.dataSavedShared,
    required this.dataShared,
    required this.dontAllow,
    required this.empty,
    required this.findOurTermsOfServicePrivacyPolicyAt,
    required this.forMoreInformationAboutThisError,
    required this.gettingReady,
    required this.gettingReadyToVerify,
    required this.inappSdkVersionIsOutdatedAndNotFunctionalAnymore,
    required this.infinite,
    required this.invalidLink,
    required this.loading,
    required this.lookingForInformationToVerify,
    required this.noProvidersFound,
    required this.notAvailable,
    required this.ok,
    required this.orBrowseSomeOfOur,
    required this.outdated,
    required this.pasteTheRequestedProofLinkHere,
    required this.platformNotSupported,
    required this.pleaseHoldOnForJustALittleLonger,
    required this.privacy,
    required this.privacyPolicy,
    required this.proofGenerationWasCancelledByTheUser,
    required this.proofSubmissionFailed,
    required this.proofsGeneratedByReclaimProtocolAreSecureAndPrivate,
    required this.providerNotFound,
    required this.providers,
    required this.refreshPage,
    required this.requestingPermission,
    required this.requirementForVerificationCouldNotBeMet,
    required this.saveWebsiteData,
    required this.searchForAProvider,
    required this.sessionExpired,
    required this.settings,
    required this.share,
    required this.shareData,
    required this.shareRequests,
    required this.somethingWentWrong,
    required this.submit,
    required this.tapOnTheLinkOnTheOtherAppBrowser,
    required this.tapShareToSendForManualReview,
    required this.termsOfService,
    required this.theApplicationHasEncounteredAnUnknownError,
    required this.theRequestedProofLinkIsInvalid,
    required this.thisDeviceIsNotSupportedForVerifications,
    required this.thisMightTakeAFewSeconds,
    required this.thisShouldntTakeMuchLonger,
    required this.thisVersionOfAppIsNotSupportedAnymore,
    required this.troubleshootingMode,
    required this.tryAgain,
    required this.unsupportedDevice,
    required this.updateForInappSdkAvailableCritical,
    required this.updateForInappSdkAvailableWarning,
    required this.verificationCancelled,
    required this.verificationDismissedByUser,
    required this.verificationFailed,
    required this.verifyAgain,
    required this.waitingForVerification,
    required this.wereReviewingYourSubmission,
    required this.whatWasShared,
    required this.whatWentWrong,
    required this.why,
    required this.youAlwaysControlWhoYouShareYourDataWith,
    required this.youAreInCompleteControlOfYourData,
    required this.youPreviouslyVerifiedThisData,
    required this.yourDataHasBeenSubmittedSuccessfully,
    required this.isRequestingADataFromString,
    required this.returnToString,
    required this.sharingWithString,
    required this.unexpectedErrorOccurredDuringVerificationString,
    required this.verificationRequestInvalidString,
    required this.verificationSessionExpiredString,
    required this.verifyingDataFromString,
    required this.wantsToAccessYourString,
    required this.youCanNowReturnToString,
    required this.yourLoginCredentialsAndPrivateDataStaySecureString,
    required this.defaultLanguage,
    required this.languageName,
    required this.changeLanguage,
    required this.searchByProvider,
    required this.hideDetails,
    required this.invalidVerificationRequest,
    required this.verifyingForString,
    required this.viewDetails,
    required this.waitingForVerificationStart,
    required this.weCouldntDeliverProofsString,
    required this.verifyingStudentStatusString,
  }) : super(locale);

  final String locale;

  @override
  final String helloWorld;

  factory RemoteLocalizations.fromJson(dynamic data) => _$RemoteLocalizationsFromJson(data);
  Map<String, dynamic> toJson() => _$RemoteLocalizationsToJson(this);

  @override
  final String allow;

  @override
  final String almostThereJustFinalizingTheDetails;

  @override
  final String anUnknownProblemOccurred;

  @override
  final String areYouSureYouSeeAllTheDataThatNeedsVerification;

  @override
  final String byContinuingYouAgreeToThese;

  @override
  final String contactApplicationSupportForMoreInformation;

  @override
  final String copiedToYourClipboard;

  @override
  final String copySessionId;

  @override
  final String createAndVerifyDataInSeconds;

  @override
  final String dataSavedShared;

  @override
  final String dataShared;

  @override
  final String dontAllow;

  @override
  final String empty;

  @override
  final String findOurTermsOfServicePrivacyPolicyAt;

  @override
  final String forMoreInformationAboutThisError;

  @override
  final String gettingReady;

  @override
  final String gettingReadyToVerify;

  @override
  final String inappSdkVersionIsOutdatedAndNotFunctionalAnymore;

  @override
  final String infinite;

  @override
  final String invalidLink;

  final String isRequestingADataFromString;

  @override
  String isRequestingADataFrom({required String appName, required String user}) {
    return interpolateTemplateWithValues(isRequestingADataFromString, {'appName': appName, 'user': user});
  }

  @override
  final String loading;

  @override
  final String lookingForInformationToVerify;

  @override
  final String noProvidersFound;

  @override
  final String notAvailable;

  @override
  final String ok;

  @override
  final String orBrowseSomeOfOur;

  @override
  final String outdated;

  @override
  final String pasteTheRequestedProofLinkHere;

  @override
  final String platformNotSupported;

  @override
  final String pleaseHoldOnForJustALittleLonger;

  @override
  final String privacy;

  @override
  final String privacyPolicy;

  @override
  final String proofGenerationWasCancelledByTheUser;

  @override
  final String proofSubmissionFailed;

  @override
  final String proofsGeneratedByReclaimProtocolAreSecureAndPrivate;

  @override
  final String providerNotFound;

  @override
  final String providers;

  @override
  final String refreshPage;

  @override
  final String requestingPermission;

  @override
  final String requirementForVerificationCouldNotBeMet;

  final String returnToString;

  @override
  String returnTo({required String appName}) {
    return interpolateTemplateWithValues(returnToString, {'appName': appName});
  }

  @override
  final String saveWebsiteData;

  @override
  final String searchForAProvider;

  @override
  final String sessionExpired;

  @override
  final String settings;

  @override
  final String share;

  @override
  final String shareData;

  @override
  final String shareRequests;

  final String sharingWithString;

  @override
  String sharingWith({required String appName}) {
    return interpolateTemplateWithValues(sharingWithString, {'appName': appName});
  }

  @override
  final String somethingWentWrong;

  @override
  final String submit;

  @override
  final String tapOnTheLinkOnTheOtherAppBrowser;

  @override
  final String tapShareToSendForManualReview;

  @override
  final String termsOfService;

  @override
  final String theApplicationHasEncounteredAnUnknownError;

  @override
  final String theRequestedProofLinkIsInvalid;

  @override
  final String thisDeviceIsNotSupportedForVerifications;

  @override
  final String thisMightTakeAFewSeconds;

  @override
  final String thisShouldntTakeMuchLonger;

  @override
  final String thisVersionOfAppIsNotSupportedAnymore;

  @override
  final String troubleshootingMode;

  @override
  final String tryAgain;

  final String unexpectedErrorOccurredDuringVerificationString;

  @override
  String unexpectedErrorOccurredDuringVerification({required String appName, required String message}) {
    return interpolateTemplateWithValues(unexpectedErrorOccurredDuringVerificationString, {
      'appName': appName,
      'message': message,
    });
  }

  @override
  final String unsupportedDevice;

  @override
  final String updateForInappSdkAvailableCritical;

  @override
  final String updateForInappSdkAvailableWarning;

  @override
  final String verificationCancelled;

  @override
  final String verificationDismissedByUser;

  @override
  final String verificationFailed;

  final String verificationRequestInvalidString;

  @override
  String verificationRequestInvalid({required String appName}) {
    return interpolateTemplateWithValues(verificationRequestInvalidString, {'appName': appName});
  }

  final String verificationSessionExpiredString;

  @override
  String verificationSessionExpired({required String appName}) {
    return interpolateTemplateWithValues(verificationSessionExpiredString, {'appName': appName});
  }

  @override
  final String verifyAgain;

  final String verifyingDataFromString;

  @override
  String verifyingDataFrom({required String domain}) {
    return interpolateTemplateWithValues(verifyingDataFromString, {'domain': domain});
  }

  @override
  final String waitingForVerification;

  final String wantsToAccessYourString;

  @override
  String wantsToAccessYour({required String domain, required String resource}) {
    return interpolateTemplateWithValues(wantsToAccessYourString, {'domain': domain, 'resource': resource});
  }

  @override
  final String wereReviewingYourSubmission;

  @override
  final String whatWasShared;

  @override
  final String whatWentWrong;

  @override
  final String why;

  @override
  final String youAlwaysControlWhoYouShareYourDataWith;

  @override
  final String youAreInCompleteControlOfYourData;

  final String youCanNowReturnToString;

  @override
  String youCanNowReturnTo({required String appName}) {
    return interpolateTemplateWithValues(youCanNowReturnToString, {'appName': appName});
  }

  @override
  final String youPreviouslyVerifiedThisData;

  @override
  final String yourDataHasBeenSubmittedSuccessfully;

  final String yourLoginCredentialsAndPrivateDataStaySecureString;

  @override
  String yourLoginCredentialsAndPrivateDataStaySecure({required Object appName}) {
    return interpolateTemplateWithValues(yourLoginCredentialsAndPrivateDataStaySecureString, {
      'appName': appName.toString(),
    });
  }

  @override
  final String defaultLanguage;

  @override
  final String languageName;

  @override
  final String changeLanguage;

  @override
  final String searchByProvider;

  @override
  final String hideDetails;

  @override
  final String invalidVerificationRequest;
  final String verifyingForString;

  @override
  String verifyingFor({required String appName}) {
    return interpolateTemplateWithValues(verifyingForString, {'appName': appName});
  }

  @override
  final String viewDetails;

  @override
  final String waitingForVerificationStart;
  final String weCouldntDeliverProofsString;

  @override
  String weCouldntDeliverProofs({required String appName}) {
    return interpolateTemplateWithValues(weCouldntDeliverProofsString, {'appName': appName});
  }

  final String verifyingStudentStatusString;
  @override
  String verifyingStudentStatus({required String providerName}) {
    return interpolateTemplateWithValues(verifyingStudentStatusString, {'providerName': providerName});
  }
}
