import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:fluttertoast/fluttertoast.dart';

import '../assets/assets.dart';
import 'svg_icon.dart';

class WebviewBottomBar
    extends StatelessWidget {
  final String
      sessionId;
  final EdgeInsetsGeometry
      padding;
  final MainAxisSize
      mainAxisSize;

  const WebviewBottomBar({
    super.key,
    required this.sessionId,
    this.padding = const EdgeInsets
        .symmetric(
        vertical: 8,
        horizontal: 8),
    this.mainAxisSize =
        MainAxisSize.max,
  });

  @override
  Widget build(
      BuildContext
          context) {
    return GestureDetector(
      onTap:
          () {
        Clipboard.setData(ClipboardData(text: sessionId)).then((_) {
          Fluttertoast.showToast(msg: 'Copied to your clipboard!');
        });
      },
      behavior:
          HitTestBehavior.translucent,
      child:
          Padding(
        padding: padding,
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisSize: mainAxisSize,
          children: [
            const SvgImageIcon(
              $ReclaimAssetImageProvider.shieldTick,
              color: Color(0x66292929),
              size: 19,
            ),
            const SizedBox(width: 5),
            Flexible(
              child: ConstrainedBox(
                constraints: const BoxConstraints(maxHeight: 15),
                child: FittedBox(
                  fit: BoxFit.scaleDown,
                  child: Text(
                    sessionId.isNotEmpty ? sessionId : 'Proofs generated by Reclaim Protocol are secure and private.',
                    style: const TextStyle(
                      fontSize: 12,
                      color: Color(0x88000000),
                      fontWeight: FontWeight.w400,
                      height: 1.35,
                    ),
                    textAlign: TextAlign.start,
                    maxLines: 1,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
