// ignore_for_file: type=lint, unused_element
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

@ffi.Native<ExtractHTMLElementsIndexes_return Function(GoSlice)>()
external ExtractHTMLElementsIndexes_return ExtractHTMLElementsIndexes(GoSlice params);

@ffi.Native<ExtractJSONValueIndexes_return Function(GoSlice)>()
external ExtractJSONValueIndexes_return ExtractJSONValueIndexes(GoSlice params);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void Free(ffi.Pointer<ffi.Void> pointer);

@ffi.Native<GenerateOPRFRequestData_return Function(GoSlice)>()
external GenerateOPRFRequestData_return GenerateOPRFRequestData(GoSlice params);

@ffi.Native<GetAlgorithmID_return Function(ffi.Pointer<ffi.Char>)>()
external GetAlgorithmID_return GetAlgorithmID(ffi.Pointer<ffi.Char> cipher);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedChar)>()
external ffi.Pointer<ffi.Char> GetCipherName(int algorithmID);

@ffi.Native<ffi.UnsignedChar Function(ffi.UnsignedChar, GoSlice, GoSlice)>()
external int InitAlgorithm(int algorithmID, GoSlice provingKey, GoSlice r1cs);

@ffi.Native<ffi.Bool Function(ffi.UnsignedChar)>()
external bool IsAlgorithmInitialized(int algorithmID);

@ffi.Native<ffi.Void Function(ffi.UnsignedChar, ffi.Bool)>()
external void MarkZKInitComplete(int algorithmID, bool success);

@ffi.Native<Prove_return Function(GoSlice)>()
external Prove_return Prove(GoSlice params);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.UnsignedChar algorithm_id)>>)>()
external void SetZKInitCallback(
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.UnsignedChar algorithm_id)>> callback,
);

@ffi.Native<TOPRFFinalize_return Function(GoSlice)>()
external TOPRFFinalize_return TOPRFFinalize(GoSlice params);

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void _Exit(int arg0);

@ffi.Native<ffi.Size Function(_GoString_)>()
external int _GoStringLen(_GoString_ s);

@ffi.Native<ffi.Pointer<ffi.Char> Function(_GoString_)>()
external ffi.Pointer<ffi.Char> _GoStringPtr(_GoString_ s);

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.Char>)>()
external int a64l(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Void Function()>()
external void abort();

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int abs(int arg0);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>()
external ffi.Pointer<ffi.Void> aligned_alloc(int __alignment, int __size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> alloca(int __size);

@ffi.Native<ffi.Uint32 Function()>()
external int arc4random();

@Deprecated('use arc4random_stir')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.UnsignedChar>, ffi.Int)>()
external void arc4random_addrandom(ffi.Pointer<ffi.UnsignedChar> arg0, int __datlen);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external void arc4random_buf(ffi.Pointer<ffi.Void> __buf, int __nbytes);

@ffi.Native<ffi.Void Function()>()
external void arc4random_stir();

@ffi.Native<ffi.Uint32 Function(ffi.Uint32)>()
external int arc4random_uniform(int __upper_bound);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>()
external int at_quick_exit(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>()
external int atexit(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> arg0);

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.Char>)>()
external double atof(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int atoi(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.Char>)>()
external int atol(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.LongLong Function(ffi.Pointer<ffi.Char>)>()
external int atoll(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>,
  )
>()
external ffi.Pointer<ffi.Void> bsearch(
  ffi.Pointer<ffi.Void> __key,
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>> __compar,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>()
external ffi.Pointer<ffi.Void> calloc(int __count, int __size);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> cgetcap(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Char> arg1, int arg2);

@ffi.Native<ffi.Int Function()>()
external int cgetclose();

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)
>()
external int cgetent(
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg1,
  ffi.Pointer<ffi.Char> arg2,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int cgetfirst(ffi.Pointer<ffi.Pointer<ffi.Char>> arg0, ffi.Pointer<ffi.Pointer<ffi.Char>> arg1);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int cgetmatch(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Char> arg1);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int cgetnext(ffi.Pointer<ffi.Pointer<ffi.Char>> arg0, ffi.Pointer<ffi.Pointer<ffi.Char>> arg1);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Long>)>()
external int cgetnum(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Char> arg1, ffi.Pointer<ffi.Long> arg2);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int cgetset(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int cgetstr(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Char> arg1, ffi.Pointer<ffi.Pointer<ffi.Char>> arg2);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int cgetustr(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Char> arg1, ffi.Pointer<ffi.Pointer<ffi.Char>> arg2);

@ffi.Native<ffi.Void Function()>()
external void clear_log_callback();

@Deprecated('Use posix_spawn APIs instead.')
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int daemon(int arg0, int arg1);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int, ffi.UnsignedShort)>()
external ffi.Pointer<ffi.Char> devname(int arg0, int arg1);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int, ffi.UnsignedShort, ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> devname_r(int arg0, int arg1, ffi.Pointer<ffi.Char> buf, int len);

@ffi.Native<ffi.Void Function()>()
external void disable_native_networking();

@ffi.Native<div_t Function(ffi.Int, ffi.Int)>()
external div_t div(int arg0, int arg1);

@ffi.Native<ffi.Double Function()>()
external double drand48();

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Double, ffi.Int, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.Char> ecvt(double arg0, int arg1, ffi.Pointer<ffi.Int> arg2, ffi.Pointer<ffi.Int> arg3);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int64 req_id, ffi.Int conn_type, ffi.Pointer<ffi.Char> url, ffi.Int timeout_ms)
      >
    >,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int64 req_id, ffi.Pointer<ffi.Void> handle, ffi.Int max_bytes, ffi.Int timeout_ms)
      >
    >,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Int64 req_id,
          ffi.Pointer<ffi.Void> handle,
          ffi.Pointer<ffi.UnsignedChar> data,
          ffi.Int length,
        )
      >
    >,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> handle)>>,
  )
>()
external int enable_native_networking(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Int64 req_id, ffi.Int conn_type, ffi.Pointer<ffi.Char> url, ffi.Int timeout_ms)
    >
  >
  connectCb,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Int64 req_id, ffi.Pointer<ffi.Void> handle, ffi.Int max_bytes, ffi.Int timeout_ms)
    >
  >
  readCb,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Int64 req_id,
        ffi.Pointer<ffi.Void> handle,
        ffi.Pointer<ffi.UnsignedChar> data,
        ffi.Int length,
      )
    >
  >
  writeCb,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> handle)>> closeCb,
);

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.UnsignedShort>)>()
external double erand48(ffi.Pointer<ffi.UnsignedShort> arg0);

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void exit(int arg0);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Double, ffi.Int, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.Char> fcvt(double arg0, int arg1, ffi.Pointer<ffi.Int> arg2, ffi.Pointer<ffi.Int> arg3);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void free(ffi.Pointer<ffi.Void> arg0);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Double, ffi.Int, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> gcvt(double arg0, int arg1, ffi.Pointer<ffi.Char> arg2);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Long>)>()
external ffi.Pointer<ffi.Char> getbsize(ffi.Pointer<ffi.Int> arg0, ffi.Pointer<ffi.Long> arg1);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> getenv(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int getiopolicy_np(int arg0, int arg1);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Double>, ffi.Int)>()
external int getloadavg(ffi.Pointer<ffi.Double> arg0, int __nelem);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.UnsignedInt)>()
external int getpriority(int arg0, int arg1);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> getprogname();

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<rlimit>)>()
external int getrlimit(int arg0, ffi.Pointer<rlimit> arg1);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<rusage>)>()
external int getrusage(int arg0, ffi.Pointer<rusage> arg1);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
  )
>()
external int getsubopt(
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg0,
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg1,
  ffi.Pointer<ffi.Pointer<ffi.Char>> arg2,
);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int grantpt(int arg0);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>,
  )
>()
external int heapsort(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>> __compar,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt, ffi.Pointer<ffi.Char>, ffi.Size)>()
external ffi.Pointer<ffi.Char> initstate(int arg0, ffi.Pointer<ffi.Char> arg1, int __size);

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.UnsignedShort>)>()
external int jrand48(ffi.Pointer<ffi.UnsignedShort> arg0);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Long)>()
external ffi.Pointer<ffi.Char> l64a(int arg0);

@ffi.Native<ffi.Long Function(ffi.Long)>()
external int labs(int arg0);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.UnsignedShort>)>()
external void lcong48(ffi.Pointer<ffi.UnsignedShort> arg0);

@ffi.Native<ldiv_t Function(ffi.Long, ffi.Long)>()
external ldiv_t ldiv(int arg0, int arg1);

@ffi.Native<ffi.LongLong Function(ffi.LongLong)>()
external int llabs(int arg0);

@ffi.Native<lldiv_t Function(ffi.LongLong, ffi.LongLong)>()
external lldiv_t lldiv(int arg0, int arg1);

@ffi.Native<ffi.Long Function()>()
external int lrand48();

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> malloc(int __size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_aligned_alloc(int alignment, int size, int type_id);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_calloc(int count, int size, int type_id);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.UnsignedLongLong)>()
external void malloc_type_free(ffi.Pointer<ffi.Void> ptr, int type_id);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_malloc(int size, int type_id);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Void>>, ffi.Size, ffi.Size, ffi.UnsignedLongLong)>()
external int malloc_type_posix_memalign(
  ffi.Pointer<ffi.Pointer<ffi.Void>> memptr,
  int alignment,
  int size,
  int type_id,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_realloc(ffi.Pointer<ffi.Void> ptr, int size, int type_id);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_valloc(int size, int type_id);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<_malloc_zone_t>, ffi.Size, ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_zone_calloc(
  ffi.Pointer<_malloc_zone_t> zone,
  int count,
  int size,
  int type_id,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<_malloc_zone_t>, ffi.Pointer<ffi.Void>, ffi.UnsignedLongLong)>()
external void malloc_type_zone_free(ffi.Pointer<_malloc_zone_t> zone, ffi.Pointer<ffi.Void> ptr, int type_id);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<_malloc_zone_t>, ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_zone_malloc(ffi.Pointer<_malloc_zone_t> zone, int size, int type_id);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<_malloc_zone_t>, ffi.Size, ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_zone_memalign(
  ffi.Pointer<_malloc_zone_t> zone,
  int alignment,
  int size,
  int type_id,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<_malloc_zone_t>, ffi.Pointer<ffi.Void>, ffi.Size, ffi.UnsignedLongLong)
>()
external ffi.Pointer<ffi.Void> malloc_type_zone_realloc(
  ffi.Pointer<_malloc_zone_t> zone,
  ffi.Pointer<ffi.Void> ptr,
  int size,
  int type_id,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<_malloc_zone_t>, ffi.Size, ffi.UnsignedLongLong)>()
external ffi.Pointer<ffi.Void> malloc_type_zone_valloc(ffi.Pointer<_malloc_zone_t> zone, int size, int type_id);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Size)>()
external int mblen(ffi.Pointer<ffi.Char> __s, int __n);

@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Char>, ffi.Size)>()
external int mbstowcs(ffi.Pointer<ffi.WChar> arg0, ffi.Pointer<ffi.Char> arg1, int __n);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Char>, ffi.Size)>()
external int mbtowc(ffi.Pointer<ffi.WChar> arg0, ffi.Pointer<ffi.Char> arg1, int __n);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>,
  )
>()
external int mergesort(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>> __compar,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int mkstemp(ffi.Pointer<ffi.Char> arg0);

@Deprecated(
  'This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of mktemp(3), it is highly recommended that you use mkstemp(3) instead.',
)
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> mktemp(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Long Function()>()
external int mrand48();

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.UnsignedShort>)>()
external int nrand48(ffi.Pointer<ffi.UnsignedShort> arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Void>>, ffi.Size, ffi.Size)>()
external int posix_memalign(ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr, int __alignment, int __size);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int posix_openpt(int arg0);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>,
  )
>()
external void psort(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>> __compar,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>
    >,
  )
>()
external void psort_r(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.Void> arg3,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>
  __compar,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> ptsname(int arg0);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.Size)>()
external int ptsname_r(int fildes, ffi.Pointer<ffi.Char> buffer, int buflen);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int putenv(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>,
  )
>()
external void qsort(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>> __compar,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Size,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<
      ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>
    >,
  )
>()
external void qsort_r(
  ffi.Pointer<ffi.Void> __base,
  int __nel,
  int __width,
  ffi.Pointer<ffi.Void> arg3,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>
  __compar,
);

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void quick_exit(int arg0);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>, ffi.Int, ffi.Pointer<ffi.UnsignedChar>, ffi.UnsignedInt)
>()
external int radixsort(
  ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>> __base,
  int __nel,
  ffi.Pointer<ffi.UnsignedChar> __table,
  int __endbyte,
);

@ffi.Native<ffi.Int Function()>()
external int rand();

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.UnsignedInt>)>()
external int rand_r(ffi.Pointer<ffi.UnsignedInt> arg0);

@ffi.Native<ffi.Long Function()>()
external int random();

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external ffi.Pointer<ffi.Void> realloc(ffi.Pointer<ffi.Void> __ptr, int __size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external ffi.Pointer<ffi.Void> reallocf(ffi.Pointer<ffi.Void> __ptr, int __size);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> realpath(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Char> arg1);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Int>,
  )
>(symbol: 'reclaim_execute_protocol')
external int _reclaim_execute_protocol(
  ffi.Pointer<ffi.Char> request_json,
  ffi.Pointer<ffi.Char> config_json,
  ffi.Pointer<ffi.Pointer<ffi.Char>> claim_json,
  ffi.Pointer<ffi.Int> claim_length,
);

reclaim_error_t reclaim_execute_protocol(
  ffi.Pointer<ffi.Char> request_json,
  ffi.Pointer<ffi.Char> config_json,
  ffi.Pointer<ffi.Pointer<ffi.Char>> claim_json,
  ffi.Pointer<ffi.Int> claim_length,
) {
  return reclaim_error_t.fromValue(_reclaim_execute_protocol(request_json, config_json, claim_json, claim_length));
}

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void reclaim_free_string(ffi.Pointer<ffi.Char> str);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>(symbol: 'reclaim_get_error_message')
external ffi.Pointer<ffi.Char> _reclaim_get_error_message(int error);

ffi.Pointer<ffi.Char> reclaim_get_error_message(reclaim_error_t error) {
  return _reclaim_get_error_message(error.value);
}

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> reclaim_get_version();

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int rpmatch(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Pointer<ffi.UnsignedShort> Function(ffi.Pointer<ffi.UnsignedShort>)>()
external ffi.Pointer<ffi.UnsignedShort> seed48(ffi.Pointer<ffi.UnsignedShort> arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int set_log_callback(ffi.Pointer<ffi.Void> callback);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Int)>()
external int setenv(ffi.Pointer<ffi.Char> __name, ffi.Pointer<ffi.Char> __value, int __overwrite);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>()
external int setiopolicy_np(int arg0, int arg1, int arg2);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void setkey(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.UnsignedInt, ffi.Int)>()
external int setpriority(int arg0, int arg1, int arg2);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void setprogname(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<rlimit>)>()
external int setrlimit(int arg0, ffi.Pointer<rlimit> arg1);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> setstate(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int)>> Function(
    ffi.Int,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int)>> signal(
  int arg0,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int)>> arg1,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>, ffi.Int, ffi.Pointer<ffi.UnsignedChar>, ffi.UnsignedInt)
>()
external int sradixsort(
  ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>> __base,
  int __nel,
  ffi.Pointer<ffi.UnsignedChar> __table,
  int __endbyte,
);

@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void srand(int arg0);

@ffi.Native<ffi.Void Function(ffi.Long)>()
external void srand48(int arg0);

@ffi.Native<ffi.Void Function()>()
external void sranddev();

@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>()
external void srandom(int arg0);

@ffi.Native<ffi.Void Function()>()
external void srandomdev();

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Char> level,
          ffi.Pointer<ffi.Char> message,
          ffi.Pointer<ffi.Char> fields,
          ffi.Int progress_percentage,
          ffi.Pointer<ffi.Char> progress_description,
        )
      >
    >,
  )
>()
external void store_log_callback(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Char> level,
        ffi.Pointer<ffi.Char> message,
        ffi.Pointer<ffi.Char> fields,
        ffi.Int progress_percentage,
        ffi.Pointer<ffi.Char> progress_description,
      )
    >
  >
  callback,
);

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external double strtod(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Pointer<ffi.Char>> arg1);

@ffi.Native<ffi.Float Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external double strtof(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.Pointer<ffi.Char>> arg1);

@ffi.Native<ffi.Long Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>()
external int strtol(ffi.Pointer<ffi.Char> __str, ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr, int __base);

@ffi.Native<ffi.LongLong Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>()
external int strtoll(ffi.Pointer<ffi.Char> __str, ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr, int __base);

@ffi.Native<
  ffi.LongLong Function(ffi.Pointer<ffi.Char>, ffi.LongLong, ffi.LongLong, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external int strtonum(
  ffi.Pointer<ffi.Char> __numstr,
  int __minval,
  int __maxval,
  ffi.Pointer<ffi.Pointer<ffi.Char>> __errstrp,
);

@ffi.Native<ffi.LongLong Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>()
external int strtoq(ffi.Pointer<ffi.Char> __str, ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr, int __base);

@ffi.Native<ffi.UnsignedLong Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>()
external int strtoul(ffi.Pointer<ffi.Char> __str, ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr, int __base);

@ffi.Native<ffi.UnsignedLongLong Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>()
external int strtoull(ffi.Pointer<ffi.Char> __str, ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr, int __base);

@ffi.Native<ffi.UnsignedLongLong Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>()
external int strtouq(ffi.Pointer<ffi.Char> __str, ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr, int __base);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Void>, ffi.Int, ffi.Pointer<ffi.Char>)>()
external void submit_connect_result(
  int req_id,
  ffi.Pointer<ffi.Void> handle,
  int err_code,
  ffi.Pointer<ffi.Char> err_msg,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.UnsignedChar>, ffi.Int, ffi.Int)>()
external void submit_read_result(int req_id, ffi.Pointer<ffi.UnsignedChar> data, int length, int err_code);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Int, ffi.Int)>()
external void submit_write_result(int req_id, int bytes_written, int err_code);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int system(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Int Function(ffi.Int)>()
external int unlockpt(int arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int unsetenv(ffi.Pointer<ffi.Char> arg0);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> valloc(int __size);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Int>)>()
external int wait(ffi.Pointer<ffi.Int> arg0);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Int>, ffi.Int, ffi.Pointer<rusage>)>()
external int wait3(ffi.Pointer<ffi.Int> arg0, int arg1, ffi.Pointer<rusage> arg2);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Int>, ffi.Int, ffi.Pointer<rusage>)>()
external int wait4(int arg0, ffi.Pointer<ffi.Int> arg1, int arg2, ffi.Pointer<rusage> arg3);

@ffi.Native<ffi.Int Function(ffi.UnsignedInt, ffi.UnsignedInt, ffi.Pointer<__siginfo>, ffi.Int)>(symbol: 'waitid')
external int _waitid(int arg0, int arg1, ffi.Pointer<__siginfo> arg2, int arg3);

int waitid(idtype_t arg0, int arg1, ffi.Pointer<__siginfo> arg2, int arg3) {
  return _waitid(arg0.value, arg1, arg2, arg3);
}

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Int>, ffi.Int)>()
external int waitpid(int arg0, ffi.Pointer<ffi.Int> arg1, int arg2);

@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.WChar>, ffi.Size)>()
external int wcstombs(ffi.Pointer<ffi.Char> arg0, ffi.Pointer<ffi.WChar> arg1, int __n);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.WChar)>()
external int wctomb(ffi.Pointer<ffi.Char> arg0, int arg1);

final class ExtractHTMLElementsIndexes_return extends ffi.Struct {
  external ffi.Pointer<ffi.Void> r0;

  @ffi.LongLong()
  external int r1;

  static ffi.Pointer<ExtractHTMLElementsIndexes_return> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> r0,
    required int r1,
  }) => $allocator<ExtractHTMLElementsIndexes_return>()
    ..ref.r0 = r0
    ..ref.r1 = r1;
}

final class ExtractJSONValueIndexes_return extends ffi.Struct {
  external ffi.Pointer<ffi.Void> r0;

  @ffi.LongLong()
  external int r1;

  static ffi.Pointer<ExtractJSONValueIndexes_return> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> r0,
    required int r1,
  }) => $allocator<ExtractJSONValueIndexes_return>()
    ..ref.r0 = r0
    ..ref.r1 = r1;
}

final class GenerateOPRFRequestData_return extends ffi.Struct {
  external ffi.Pointer<ffi.Void> r0;

  @ffi.LongLong()
  external int r1;

  static ffi.Pointer<GenerateOPRFRequestData_return> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> r0,
    required int r1,
  }) => $allocator<GenerateOPRFRequestData_return>()
    ..ref.r0 = r0
    ..ref.r1 = r1;
}

final class GetAlgorithmID_return extends ffi.Struct {
  @ffi.UnsignedChar()
  external int r0;

  @ffi.Bool()
  external bool r1;

  static ffi.Pointer<GetAlgorithmID_return> $allocate(ffi.Allocator $allocator, {required int r0, required bool r1}) =>
      $allocator<GetAlgorithmID_return>()
        ..ref.r0 = r0
        ..ref.r1 = r1;
}

final class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @ffi.LongLong()
  external int len;

  @ffi.LongLong()
  external int cap;

  static ffi.Pointer<GoSlice> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> data,
    required int len,
    required int cap,
  }) => $allocator<GoSlice>()
    ..ref.data = data
    ..ref.len = len
    ..ref.cap = cap;
}

final class Prove_return extends ffi.Struct {
  external ffi.Pointer<ffi.Void> r0;

  @ffi.LongLong()
  external int r1;

  static ffi.Pointer<Prove_return> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> r0,
    required int r1,
  }) => $allocator<Prove_return>()
    ..ref.r0 = r0
    ..ref.r1 = r1;
}

final class TOPRFFinalize_return extends ffi.Struct {
  external ffi.Pointer<ffi.Void> r0;

  @ffi.LongLong()
  external int r1;

  static ffi.Pointer<TOPRFFinalize_return> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> r0,
    required int r1,
  }) => $allocator<TOPRFFinalize_return>()
    ..ref.r0 = r0
    ..ref.r1 = r1;
}

final class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ffi.Long()
  external int n;
}

final class __siginfo extends ffi.Opaque {}

final class _malloc_zone_t extends ffi.Opaque {}

final class div_t extends ffi.Struct {
  @ffi.Int()
  external int quot;

  @ffi.Int()
  external int rem;

  static ffi.Pointer<div_t> $allocate(ffi.Allocator $allocator, {required int quot, required int rem}) =>
      $allocator<div_t>()
        ..ref.quot = quot
        ..ref.rem = rem;
}

enum idtype_t {
  P_ALL(0),
  P_PID(1),
  P_PGID(2);

  final int value;
  const idtype_t(this.value);

  static idtype_t fromValue(int value) => switch (value) {
    0 => P_ALL,
    1 => P_PID,
    2 => P_PGID,
    _ => throw ArgumentError('Unknown value for idtype_t: $value'),
  };
}

final class ldiv_t extends ffi.Struct {
  @ffi.Long()
  external int quot;

  @ffi.Long()
  external int rem;

  static ffi.Pointer<ldiv_t> $allocate(ffi.Allocator $allocator, {required int quot, required int rem}) =>
      $allocator<ldiv_t>()
        ..ref.quot = quot
        ..ref.rem = rem;
}

final class lldiv_t extends ffi.Struct {
  @ffi.LongLong()
  external int quot;

  @ffi.LongLong()
  external int rem;

  static ffi.Pointer<lldiv_t> $allocate(ffi.Allocator $allocator, {required int quot, required int rem}) =>
      $allocator<lldiv_t>()
        ..ref.quot = quot
        ..ref.rem = rem;
}

enum reclaim_error_t {
  RECLAIM_SUCCESS(0),
  RECLAIM_ERROR_INVALID_ARGS(-1),
  RECLAIM_ERROR_CONNECTION_FAILED(-2),
  RECLAIM_ERROR_PROTOCOL_FAILED(-3),
  RECLAIM_ERROR_TIMEOUT(-4),
  RECLAIM_ERROR_MEMORY(-5),
  RECLAIM_ERROR_SESSION_NOT_FOUND(-6),
  RECLAIM_ERROR_ALREADY_COMPLETED(-7);

  final int value;
  const reclaim_error_t(this.value);

  static reclaim_error_t fromValue(int value) => switch (value) {
    0 => RECLAIM_SUCCESS,
    -1 => RECLAIM_ERROR_INVALID_ARGS,
    -2 => RECLAIM_ERROR_CONNECTION_FAILED,
    -3 => RECLAIM_ERROR_PROTOCOL_FAILED,
    -4 => RECLAIM_ERROR_TIMEOUT,
    -5 => RECLAIM_ERROR_MEMORY,
    -6 => RECLAIM_ERROR_SESSION_NOT_FOUND,
    -7 => RECLAIM_ERROR_ALREADY_COMPLETED,
    _ => throw ArgumentError('Unknown value for reclaim_error_t: $value'),
  };
}

final class rlimit extends ffi.Opaque {}

final class rusage extends ffi.Opaque {}
